---
title: "Chinese"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(jiebaR)
library(rjson)
result <- fromJSON(file = "Reduced_dict.json")
cutter = worker()


#produce pinyin
pinyin_produce = function(input) {
  return(result[input])
}

ui <- fluidPage( 
  #Name of the app
  headerPanel("Learn Chinese"),
  
  # Layout of the sidebar
  sidebarLayout(
    sidebarPanel(
      textInput("Chinese", "Please enter Chinese")
      ),
  mainPanel(
      textOutput("text")
    )),  
  
#)
)

#save the output that I build by output$
#build the output by using render function
server <- function(input, output, session) {
  output$text = renderText({
    "你好"
    paste0(input, result[input]$pinyin)
  })
  
# 
#   output$pinyin = {(
#     renderText()
#   )
#   }
}



# output$selected_var <- renderText({ 
#     paste("You have selected", input$var)
#   })
shinyApp(ui = ui, server = server )
```

```{r}
library(jiebaR)
cutter = worker()
  
a = segment("我是中国人!" , cutter )
typeof(a)
a[1]

library("rjson")
result <- fromJSON(file = "Reduced_dict.json")
# print(result$"2019冠状病毒病")
# 
# grepl("ā", "āi", fixed=TRUE)
# 
pinyin_produce = function(input) {
  return(result[input])
}

typeof(result$一手遮天$pinyin)

a = pinyin_produce("你好")
a$你好$pinyin
# 
# a = "你好"
# result[a]

# The function that checks the tone
check_tone = function(input) {
  #first tone
  if (grepl("ā", input, fixed=TRUE) || grepl("ī", input, fixed=TRUE) || grepl("ū", input, fixed=TRUE) || grepl("ē", input, fixed=TRUE) || grepl("ō", input, fixed=TRUE)) {
    return(1)
  }
  #second tone
  else if (grepl("á", input, fixed=TRUE) || grepl("í", input, fixed=TRUE) || grepl("ú", input, fixed=TRUE) || grepl("é", input, fixed=TRUE) || grepl("ó", input, fixed=TRUE)) {
    return(2)
  }
  #third tone
  else if (grepl("ǎ", input, fixed=TRUE) || grepl("ǐ", input, fixed=TRUE) || grepl("ǔ", input, fixed=TRUE) || grepl("ě", input, fixed=TRUE) || grepl("ǒ", input, fixed=TRUE)) {
    return(3)
    }
  #fourth tone
  else if (grepl("à", input, fixed=TRUE) || grepl("ì", input, fixed=TRUE) || grepl("ù", input, fixed=TRUE) || grepl("è", input, fixed=TRUE) || grepl("ò", input, fixed=TRUE)) {
    return(4)
  }
  #neutral tone
  else if (grepl("a", input, fixed=TRUE) || grepl("i", input, fixed=TRUE) || grepl("u", input, fixed=TRUE) || grepl("e", input, fixed=TRUE) || grepl("o", input, fixed=TRUE)) {
    return(5)
  }
}

#Separate words by .,?!

# 
check_tone("hǒu")
```



