---
title: "Shapefile_cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rgdal)
library(tidyverse)
library(readr)
library(maps)

Health_Data = read_csv("~/Desktop/CS/CSC324_individual/CSC324_project_data.csv")

# The first column is unnecessary
health_data = dplyr::select(Health_Data, -1)

# In order to eliminate the other U.S. territory, read the data that only contains contiguous US land
county_map = map_data("county")
county_name_list = unique(county_map$subregion)

# Match the format of county names to merge
health_data$County = tolower(health_data$County)
health_data = subset(health_data, health_data$County %in% county_name_list)

# In order to add longitude and latitude
geo_data = read_csv("~/Desktop/CS/Grinnell/uscounties.csv")
names(geo_data)[names(geo_data) == 'county_fips'] = 'FIPS'

# Drop unnecessary columns 
geo_data = dplyr::select(geo_data, 4, 7, 8)

# Merge longitude and latitude to the existent variables
health_data2 = inner_join(geo_data, health_data, by = "FIPS")
health_data2

# Add other attributes
county_map <- readOGR(
  dsn= "~/Desktop/CS/Grinnell/county_low",
  layer="county_boundaries",
)

# We keep the format of shapefile
names(health_data2)[names(health_data2) == 'FIPS'] = 'GEOID'

geoid = left_join(county_map@data, health_data2, by = "GEOID", suffix = c('', ''))
county_attributes =  select(geoid, -1, -2, -3, -4, -5, -6, -7, -8, -9, -13)
variable_name = colnames(county_attributes)

# Assign new fields to the shapefile
for(i in 1:length(variable_name)) {                                  
  county_map@data[ , ncol(county_map@data) + 1] <- county_attributes[i]                
  colnames(county_map@data)[ncol(county_map@data)] <- variable_name[i]  
}

# Export the new shapefile
writeOGR(county_map, "~/Desktop/CS/Grinnell/county_final", "county_boundaries", driver = "ESRI Shapefile")

```

